version: '3'

services: 
  # postgres:
  #   image: 'postgres:14.0'
  #   ports:
  #     - "5432:5432"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: users
  #     POSTGRES_EXTENSIONS: uuid-ossp
  #   volumes:
  #     - ./db-data/postgres/:/var/lib/postgresql/data/
# mongo-service - handles saving all logging from all services
  # mongo:
  #   image: 'mongo'
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: logs
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./db-data/mongo/:/data/db

#redis-cache: saving a value by key on a range time. i.e: 15', 30'
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/data